# ===================== Mandatory Values =======================
# The name of the SSH key to inject into cluster machines, this can be
# left blank if a user does not require SSH access to the machines
machineSSHKeyName:

# This is required, a user can pre-allocate a floating IP and set it here
# to be used by the cluster. If this is not set, a new floating IP will be
# allocated for the cluster each time it is created and clusters cannot .
apiServer:
  floatingIP:

# --------------------------- Optional Values -------------------------

controlPlane:
  # The number of control plane machines to deploy
  # For high-availability, this should be greater than 1
  # For etcd quorum, it should be odd - usually 3, or 5 for very large clusters
  machineCount: 3
  # The flavor to use for control plane machines
  machineFlavor: l3.nano

# The Kubernetes version of the cluster
# This should match the version of kubelet and kubeadm in the image
# and will be automatically updated by us
kubernetesVersion: "1.26.7"
# The name of the image to use for cluster machines
machineImage: capi-ubuntu-2004-kube-v1.26.7-2023-09-12

# Settings for node-level registry auth if using a private registry
registryAuth:
  {}
  # registry-1.docker.io:
  #   username: "<username>"
  #   password: "<password>"
